### ISSUE TITLE
Implementation of the sixth section of the landing page

### ISSUE THREAD

**Issue by alicendeh** [wtm-buea/WTM-official-website#10]
You are required to design the section  containing **our vision**

**Remember to check out the Example.txt file to know how you should  structure your code**

**Comment by Julia-yossa** [comment]
Hello would like to this. Please assign

**Comment by alicendeh** [comment]
Hello @Julia-yossa. It's been three days since you claimed this issue, but we haven't seen any PR from you yet. We need to close these issues so new issues can be created. Please can you give tell us when you'll be done?

**Comment by Julia-yossa** [comment]
Hello, Working. Will be done soon.

**Comment by Nasah-Kuma** [comment]
This was done in one of the commits
