### ISSUE TITLE
Implementation of the last section of the landing page

### ISSUE THREAD

**Issue by alicendeh** [wtm-buea/WTM-official-website#11]
The last section is the section containing the *Footer**

**Remember to check out the Example.txt file to know how you should  structure your code**

**Comment by lonewolf9277** [comment]
Hello may I work on this?

**Comment by alicendeh** [comment]
I'll assigned the issue to you @lonewolf9277. Go ahead and work on it

**Comment by alicendeh** [comment]
Hello @lonewolf9277. It's been three days since you claimed this issue, but we haven't seen any PR from you yet. We need to close these issues so new issues can be created. Please can you give tell us when you'll be done?
