### ISSUE TITLE
Creating the Navbar

### ISSUE THREAD

**Issue by alicendeh** [wtm-buea/WTM-official-website#5]
You are required to create the navbar and make it mobile responsive. Use the resources found in the assets folder of the repo in other to work.

**Comment by alicendeh** [comment]
Hello @mohitbalwani, This project is to encourage ladies from the Women tech maker Buea community to get engaged in Open source contributions. For this reason, only community members are allowed to contribute.

**Comment by baya-lemuelle** [comment]
I would like to work on this issue. I'm a community member.

**Comment by alicendeh** [comment]
Go ahead @baya-lemuelle the issue is yours

**Comment by Julia-yossa** [comment]
Hello , @alicendeh I have been working on this issue already. I though I was mine?

**Comment by alicendeh** [comment]
Hello @baya-lemuelle . It's been five days since you claimed this issue, but we haven't seen any PR from you yet. We need to close these issues so new issues can be created. Please can you give tell us when you'll be done?
