### ISSUE TITLE
Creating the hero and making it mobile responsive

### ISSUE THREAD

**Issue by alicendeh** [wtm-buea/WTM-official-website#6]

**Comment by alicendeh** [comment]
The hero is the first section of the design on the landing page. All resources are attached to the assets folder. Feel free to tag me if there's something you don't understand.

**Comment by iGusky** [comment]
Hi!, i would like to do this issue 😄

**Comment by Nasah-Kuma** [comment]
> Go ahead @Julia-yossa .

@alicendeh  I think there has been a misunderstanding. @Julia-yossa is already working on the issue you previously assigned to another contributor. Please check again

**Comment by Julia-yossa** [comment]
Work in progress. I am still learning responsiveness and background shade. I just successfully added the icons 

![IMG_20211016_205812_184.jpg](https://user-images.githubusercontent.com/40579060/137600735-6274cf03-f40b-464f-af84-eef69d7006dc.jpg)
